version: '3.7'
services:
  master:
    image: lyasper/greenplum:6
    container_name: db_master
    environment:
      - MASTER=true
      - GP_SEG_COUNT=2
      - GP_NODE=master
      - HOSTFILE=multihost
    ports:
      - "5431:5432"
    privileged: true
    hostname: db_master
    volumes:
      - master_data:/gpdata/master
    depends_on: 
      - segment_1
      - segment_2
    command: tail -f /dev/null
    healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1

  segment_1:
    image: lyasper/greenplum:6
    container_name: db_seg_1
    environment:
      - MASTER=false
      - GP_SEG_COUNT=2
      - GP_NODE=segment
    ports:
      - "5433:5432"
    privileged: true
    hostname: db_seg_1
    volumes:
      - segment_1_data:/gpdata/segment
    command: tail -f /dev/null
    healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1

  segment_2:
    image: lyasper/greenplum:6
    container_name: db_seg_2
    environment:
      - MASTER=false
      - GP_SEG_COUNT=2
      - GP_NODE=segment
    ports:
      - "5434:5432"
    privileged: true
    hostname: db_seg_2
    volumes:
      - segment_2_data:/gpdata/segment
    command: tail -f /dev/null
    healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1

volumes:
  master_data:
  segment_1_data:
  segment_2_data:
