DROP TABLE students;

CREATE TABLE authors (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE books (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255),
	author_id INTEGER REFERENCES authors(id));
DROP TABLE authors; 

DROP TABLE authors CASCADE; 

